{
 "title": "Kyuubi",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(kyuubi_memory_usage_total_init{job=\"kyuubiserver\"},instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Kyuubi启动时间",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_start_time_seconds{job=\"kyuubiserver\"}*1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Kyuubi堆内存大小",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kyuubi_memory_usage_heap_max{job=\"kyuubiserver\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Kyuubi线程",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "kyuubi_thread_state_runnable_count",
     "legendFormat": "runnable"
    },
    {
     "expr": "kyuubi_thread_state_blocked_count\r\n",
     "legendFormat": "blocked"
    },
    {
     "expr": "kyuubi_thread_state_waiting_count\r\n",
     "legendFormat": "waiting"
    }
   ]
  },
  {
   "title": "Kyuubi执行操作的状态",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kyuubi_operation_state_ExecuteStatement_running_total",
     "legendFormat": "运行中"
    },
    {
     "expr": "kyuubi_operation_state_ExecuteStatement_finished_total",
     "legendFormat": "已完成"
    },
    {
     "expr": "kyuubi_operation_state_ExecuteStatement_error_total",
     "legendFormat": "错误"
    },
    {
     "expr": "kyuubi_operation_state_ExecuteStatement_pending_total",
     "legendFormat": "等待中"
    }
   ]
  },
  {
   "title": "Kyuubi连接数",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "targets": [
    { "expr": "kyuubi_connection_opened", "legendFormat": "连接数" }
   ]
  },
  {
   "title": "kyuubi thrift binary连接数",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "targets": [
    {
     "expr": "kyuubi_thrift_binary_connection_total",
     "legendFormat": "binary连接数"
    }
   ]
  },
  {
   "title": "Kyuubi Engine数",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 20 },
   "targets": [
    { "expr": "kyuubi_engine_total\r\n", "legendFormat": "engine数" }
   ]
  },
  {
   "title": "Kyuubi堆内存使用趋势",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 20 },
   "repeat": "memarea",
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "kyuubi_memory_usage_total_used{job=\"kyuubiserver\"}",
     "legendFormat": "已用堆内存"
    },
    {
     "expr": " kyuubi_memory_usage_total_max{job=\"kyuubiserver\"}",
     "legendFormat": "最大堆内存"
    }
   ]
  }
 ]
}