#!/bin/bash
#
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

set -x

KYUUBI_HOME="$(cd "$(dirname "$0")/.." || exit; pwd)"

function autofix_shell_scripts(){
    set +x
    echo "Start to autofix Shell scripts with shellcheck."
    script_files=(
        "./bin/beeline"
        "./bin/kyuubi"
        "./bin/kyuubi-admin"
        "./bin/kyuubi-ctl"
        "./bin/kyuubi-logo"
        "./bin/kyuubi-zk-cli"
        "./dev/reformat")
    while IFS=  read -r -d $'\0'; do
        script_files+=("$REPLY")
    done < <(find . -name "*.sh" -print0)
    for script_file in ${script_files[*]}; do
      echo "execute shellcheck on $script_file"
      shellcheck -f diff --external-sources --shell=bash "$script_file" | patch -p1
    done
    echo "Shell scripts autofix finished."
    set -x
}

# shell script style checks rely on `shellcheck` in path
if ! command -v shellcheck &> /dev/null
then
    echo "Skip Shell lint since 'shellcheck' is not available."
else
    autofix_shell_scripts
fi

PROFILES="-Pflink-provided,hive-provided,spark-provided,spark-block-cleaner,spark-3.3,spark-3.2,spark-3.1,tpcds"

# python style checks rely on `black` in path
if ! command -v black &> /dev/null
then
    echo "Skip Python lint since 'black' is not available."
else
    PROFILES="${PROFILES},spotless-python"
fi

"${KYUUBI_HOME}/build/mvn" spotless:apply $PROFILES
