{{/*
  Licensed to the Apache Software Foundation (ASF) under one or more
  contributor license agreements.  See the NOTICE file distributed with
  this work for additional information regarding copyright ownership.
  The ASF licenses this file to You under the Apache License, Version 2.0
  (the "License"); you may not use this file except in compliance with
  the License.  You may obtain a copy of the License at

     http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.
*/}}

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}
  labels:
    {{- include "kyuubi.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "kyuubi.selectorLabels" . | nindent 6 }}
  serviceName: {{ .Release.Name }}-headless
  minReadySeconds: {{ .Values.minReadySeconds }}
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  podManagementPolicy: {{ .Values.podManagementPolicy }}
  {{- with .Values.updateStrategy }}
  updateStrategy: {{- toYaml . | nindent 4 }}
  {{- end }}
  template:
    metadata:
      labels:
        {{- include "kyuubi.selectorLabels" . | nindent 8 }}
      annotations:
        checksum/conf: {{ include (print $.Template.BasePath "/kyuubi-configmap.yaml") . | sha256sum }}
        checksum/conf-hadoop: {{ include (print $.Template.BasePath "/kyuubi-hadoop-configmap.yaml") . | sha256sum }}
        {{- with .Values.podAnnotations }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets: {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if or .Values.serviceAccount.name .Values.serviceAccount.create }}
      serviceAccountName: {{ .Values.serviceAccount.name | default .Release.Name }}
      {{- end }}
      {{- if or .Values.priorityClass.name .Values.priorityClass.create }}
      priorityClassName: {{ .Values.priorityClass.name | default .Release.Name }}
      {{- end }}
      {{- with .Values.initContainers }}
      initContainers: {{- tpl (toYaml .) $ | nindent 8 }}
      {{- end }}
      containers:
        - name: kyuubi-server
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- with .Values.command }}
          command: {{- tpl (toYaml .) $ | nindent 12 }}
          {{- end }}
          {{- if .Values.args }}
          args: {{- tpl (toYaml .) $ | nindent 12 }}
          {{- else }}
          args:
            - ./bin/kyuubi
            - run
            - --conf kyuubi.kubernetes.namespace={{ .Release.Namespace }}
            - --conf kyuubi.frontend.connection.url.use.hostname=false
            - --conf kyuubi.frontend.thrift.binary.bind.port={{ .Values.server.thriftBinary.port }}
            - --conf kyuubi.frontend.thrift.http.bind.port={{ .Values.server.thriftHttp.port }}
            - --conf kyuubi.frontend.rest.bind.port={{ .Values.server.rest.port }}
            - --conf kyuubi.frontend.mysql.bind.port={{ .Values.server.mysql.port }}
            - --conf kyuubi.frontend.protocols={{ include "kyuubi.frontend.protocols" . }}
            - --conf kyuubi.metrics.enabled={{ .Values.metrics.enabled }}
            - --conf kyuubi.metrics.reporters={{ .Values.metrics.reporters }}
            - --conf kyuubi.metrics.prometheus.port={{ .Values.metrics.prometheusPort }}
          {{- end }}
          env:
            - name: KYUUBI_CONF_DIR
              value: {{ .Values.kyuubiConf.dir }}
            - name: HADOOP_CONF_DIR
              value: {{ .Values.hadoopConf.dir }}
            - name: SPARK_CONF_DIR
              value: {{ .Values.sparkConf.dir }}
            {{- with .Values.env }}
              {{- tpl (toYaml .) $ | nindent 12 }}
            {{- end }}
          {{- with .Values.envFrom }}
          envFrom: {{- tpl (toYaml .) $ | nindent 12 }}
          {{- end }}
          ports:
            {{- range $name, $frontend := .Values.server }}
            {{- if $frontend.enabled }}
            - name: {{ $name | kebabcase }}
              containerPort: {{ $frontend.port }}
            {{- end }}
            {{- end }}
            {{- if and .Values.metrics.enabled (.Values.metrics.reporters | nospace | splitList "," | has "PROMETHEUS") }}
            - name: prometheus
              containerPort: {{ .Values.metrics.prometheusPort }}
            {{- end }}
          {{- if .Values.livenessProbe.enabled }}
          livenessProbe:
            exec:
              command: ["/bin/bash", "-c", "$KYUUBI_HOME/bin/kyuubi status"]
            initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.livenessProbe.timeoutSeconds }}
            failureThreshold: {{ .Values.livenessProbe.failureThreshold }}
            successThreshold: {{ .Values.livenessProbe.successThreshold }}
          {{- end }}
          {{- if .Values.readinessProbe.enabled }}
          readinessProbe:
            exec:
              command: ["/bin/bash", "-c", "$KYUUBI_HOME/bin/kyuubi status"]
            initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.readinessProbe.timeoutSeconds }}
            failureThreshold: {{ .Values.readinessProbe.failureThreshold }}
            successThreshold: {{ .Values.readinessProbe.successThreshold }}
          {{- end }}
          {{- with .Values.resources }}
          resources: {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: conf
              mountPath: {{ .Values.kyuubiConf.dir }}
            - name: conf-hadoop
              mountPath: {{ .Values.hadoopConf.dir }}
            - name: conf-spark
              mountPath: {{ .Values.sparkConf.dir }}
            {{- with .Values.volumeMounts }}
              {{- tpl (toYaml .) $ | nindent 12 }}
            {{- end }}
        {{- with .Values.containers }}
          {{- tpl (toYaml .) $ | nindent 8 }}
        {{- end }}
      volumes:
        - name: conf
          projected:
            sources:
              - configMap:
                  name: {{ .Release.Name }}
              {{- with .Values.kyuubiConf.filesFrom }}
                {{- tpl (toYaml .) $ | nindent 14 }}
              {{- end }}
        - name: conf-hadoop
          projected:
            sources:
              - configMap:
                  name: {{ .Release.Name }}-hadoop
              {{- with .Values.hadoopConf.filesFrom }}
                {{- tpl (toYaml .) $ | nindent 14 }}
              {{- end }}
        - name: conf-spark
          projected:
            sources:
              - configMap:
                  name: {{ .Release.Name }}-spark
              {{- with .Values.sparkConf.filesFrom }}
                {{- tpl (toYaml .) $ | nindent 14 }}
              {{- end }}
        {{- with .Values.volumes }}
          {{- tpl (toYaml .) $ | nindent 8 }}
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector: {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity: {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations: {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.securityContext }}
      securityContext: {{- toYaml . | nindent 8 }}
      {{- end }}
