/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.apache.kyuubi.spark.connector.tpcds

import io.trino.tpcds.Table
import io.trino.tpcds.Table._

/**
 * Generated by TPCDSTableGenerateBenchmark
 */
object TPCDSSplitUtils {

  def getSplits(table: Table, scale: Int, splitPerTask: Int): Int = {
    val numRows = TPCDSStatisticsUtils.numRows(table, scale)
    if (TABLE_ROWS_PER_SPLIT.contains(table)) {
      (numRows.toDouble / TABLE_ROWS_PER_SPLIT(table) / splitPerTask).ceil.toInt
    } else {
      1
    }
  }

  private val TABLE_ROWS_PER_SPLIT: Map[Table, Long] = Map(
    CATALOG_RETURNS -> 730554,
    CATALOG_SALES -> 828528,
    CUSTOMER -> 1355651,
    CUSTOMER_ADDRESS -> 2077802,
    CUSTOMER_DEMOGRAPHICS -> 11190929,
    INVENTORY -> 18714768,
    STORE_RETURNS -> 846793,
    STORE_SALES -> 1077099,
    WEB_RETURNS -> 721106,
    WEB_SALES -> 800982)

}
