// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: test_case.proto

package org.apache.kyuubi.grpc.proto;

public final class TestCase {
  private TestCase() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_kyuubi_grpc_TestOpenSessionRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_kyuubi_grpc_TestOpenSessionRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_kyuubi_grpc_TestAddRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_kyuubi_grpc_TestAddRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_kyuubi_grpc_TestOpenSessionResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_kyuubi_grpc_TestOpenSessionResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_kyuubi_grpc_TestAddResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_kyuubi_grpc_TestAddResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\017test_case.proto\022\013kyuubi.grpc\"=\n\026TestOp" +
      "enSessionRequest\022\017\n\007user_id\030\001 \001(\t\022\022\n\nses" +
      "sion_id\030\002 \001(\t\"r\n\016TestAddRequest\022\017\n\007user_" +
      "id\030\001 \001(\t\022\022\n\nsession_id\030\002 \001(\t\022\024\n\014operatio" +
      "n_id\030\003 \001(\t\022\021\n\tfirst_num\030\004 \001(\003\022\022\n\nsecond_" +
      "num\030\005 \001(\003\"c\n\027TestOpenSessionResponse\022\022\n\n" +
      "session_id\030\001 \001(\t\022\036\n\026server_side_session_" +
      "id\030\002 \001(\t\022\024\n\014session_info\030\003 \001(\t\"k\n\017TestAd" +
      "dResponse\022\022\n\nsession_id\030\001 \001(\t\022\036\n\026server_" +
      "side_session_id\030\002 \001(\t\022\024\n\014operation_id\030\003 " +
      "\001(\t\022\016\n\006result\030\004 \001(\0032\271\001\n\017GrpcTestService\022" +
      "^\n\017TestOpenSession\022#.kyuubi.grpc.TestOpe" +
      "nSessionRequest\032$.kyuubi.grpc.TestOpenSe" +
      "ssionResponse\"\000\022F\n\007TestAdd\022\033.kyuubi.grpc" +
      ".TestAddRequest\032\034.kyuubi.grpc.TestAddRes" +
      "ponse\"\000B4\n\034org.apache.kyuubi.grpc.protoP" +
      "\001Z\022internal/generatedb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_kyuubi_grpc_TestOpenSessionRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_kyuubi_grpc_TestOpenSessionRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_kyuubi_grpc_TestOpenSessionRequest_descriptor,
        new String[] { "UserId", "SessionId", });
    internal_static_kyuubi_grpc_TestAddRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_kyuubi_grpc_TestAddRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_kyuubi_grpc_TestAddRequest_descriptor,
        new String[] { "UserId", "SessionId", "OperationId", "FirstNum", "SecondNum", });
    internal_static_kyuubi_grpc_TestOpenSessionResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_kyuubi_grpc_TestOpenSessionResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_kyuubi_grpc_TestOpenSessionResponse_descriptor,
        new String[] { "SessionId", "ServerSideSessionId", "SessionInfo", });
    internal_static_kyuubi_grpc_TestAddResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_kyuubi_grpc_TestAddResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_kyuubi_grpc_TestAddResponse_descriptor,
        new String[] { "SessionId", "ServerSideSessionId", "OperationId", "Result", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
