// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: test_case.proto

package org.apache.kyuubi.grpc.proto;

public interface TestAddResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:kyuubi.grpc.TestAddResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string session_id = 1;</code>
   * @return The sessionId.
   */
  String getSessionId();
  /**
   * <code>string session_id = 1;</code>
   * @return The bytes for sessionId.
   */
  com.google.protobuf.ByteString
      getSessionIdBytes();

  /**
   * <code>string server_side_session_id = 2;</code>
   * @return The serverSideSessionId.
   */
  String getServerSideSessionId();
  /**
   * <code>string server_side_session_id = 2;</code>
   * @return The bytes for serverSideSessionId.
   */
  com.google.protobuf.ByteString
      getServerSideSessionIdBytes();

  /**
   * <code>string operation_id = 3;</code>
   * @return The operationId.
   */
  String getOperationId();
  /**
   * <code>string operation_id = 3;</code>
   * @return The bytes for operationId.
   */
  com.google.protobuf.ByteString
      getOperationIdBytes();

  /**
   * <code>int64 result = 4;</code>
   * @return The result.
   */
  long getResult();
}
