#
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

# Default values for kyuubi.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Kyuubi server numbers
replicaCount: 2

# controls how Kyuubi server pods are created during initial scale up,
# when replacing pods on nodes, or when scaling down.
# The default policy is `OrderedReady`, alternative policy is `Parallel`.
podManagementPolicy: OrderedReady

# Minimum number of seconds for which a newly created kyuubi server
# should be ready without any of its container crashing for it to be considered available.
minReadySeconds: 30

# maximum number of revisions that will be maintained in the StatefulSet's revision history.
revisionHistoryLimit: 10

# indicates the StatefulSetUpdateStrategy that will be employed to update Kyuubi server Pods in the StatefulSet
# when a revision is made to Template.
updateStrategy:
  type: RollingUpdate
  rollingUpdate:
    maxUnavailable: 1
    partition: 0

image:
  repository: apache/kyuubi
  pullPolicy: IfNotPresent
  tag: ~

imagePullSecrets: []

# ServiceAccount used for Kyuubi create/list/delete pod in Kubernetes
serviceAccount:
  # Specifies whether a ServiceAccount should be created
  create: true
  # Specifies ServiceAccount name to be used (created if `create: true`)
  name: ~
  # Annotations to add to the ServiceAccount
  annotations: {}

# priorityClass used for Kyuubi server pod
priorityClass:
  # Specifies whether a priorityClass should be created
  create: false
  # Specifies priorityClass name to be used (created if `create: true`)
  name: ~
  # half of system-cluster-critical by default
  value: 1000000000

# Role-based access control
rbac:
  # Specifies whether RBAC resources should be created
  create: true
  # RBAC rules
  rules:
    - apiGroups: [""]
      resources: ["pods"]
      verbs: ["create", "list", "delete"]

server:
  # Thrift Binary protocol (HiveServer2 compatible)
  thriftBinary:
    enabled: true
    port: 10009
    service:
      type: ClusterIP
      port: "{{ .Values.server.thriftBinary.port }}"
      nodePort: ~
      annotations: {}
      # candidates are ClientIP or None
      # https://kubernetes.io/docs/reference/kubernetes-api/service-resources/service-v1/
      sessionAffinity: ~
      sessionAffinityConfig: {}
      #  sessionAffinityConfig:
      #    clientIP:
      #      timeoutSeconds: 10800

  # Thrift HTTP protocol (HiveServer2 compatible)
  thriftHttp:
    enabled: false
    port: 10010
    service:
      type: ClusterIP
      port: "{{ .Values.server.thriftHttp.port }}"
      nodePort: ~
      annotations: {}
      # candidates are ClientIP or None
      # https://kubernetes.io/docs/reference/kubernetes-api/service-resources/service-v1/
      sessionAffinity: ~
      sessionAffinityConfig: {}
      #  sessionAffinityConfig:
      #    clientIP:
      #      timeoutSeconds: 10800

  # REST API protocol (experimental)
  rest:
    enabled: true
    port: 10099
    service:
      type: ClusterIP
      port: "{{ .Values.server.rest.port }}"
      nodePort: ~
      annotations: {}
      # candidates are ClientIP or None
      # https://kubernetes.io/docs/reference/kubernetes-api/service-resources/service-v1/
      sessionAffinity: ~
      sessionAffinityConfig: {}
      #  sessionAffinityConfig:
      #    clientIP:
      #      timeoutSeconds: 10800

  # MySQL compatible text protocol (experimental)
  mysql:
    enabled: false
    port: 3309
    service:
      type: ClusterIP
      port: "{{ .Values.server.mysql.port }}"
      nodePort: ~
      annotations: {}
      # candidates are ClientIP or None
      # https://kubernetes.io/docs/reference/kubernetes-api/service-resources/service-v1/
      sessionAffinity: ~
      sessionAffinityConfig: {}
      #  sessionAffinityConfig:
      #    clientIP:
      #      timeoutSeconds: 10800

monitoring:
  # Exposes metrics in Prometheus format
  prometheus:
    enabled: true
    port: 10019

# Kyuubi configuration, see https://kyuubi.readthedocs.io/en/master/configuration/settings.html#kyuubi-configurations for more details
kyuubiConf:
  # $KYUUBI_CONF_DIR directory
  dir: /opt/kyuubi/conf
  # Configuration files from the specified keys (file name) and values (file content)
  files:
    'kyuubi-defaults.conf': |
      ## Helm chart dependent configuration
      kyuubi.kubernetes.namespace={{ .Release.Namespace }}
      kyuubi.frontend.connection.url.use.hostname=false
      kyuubi.frontend.thrift.binary.bind.port={{ .Values.server.thriftBinary.port }}
      kyuubi.frontend.thrift.http.bind.port={{ .Values.server.thriftHttp.port }}
      kyuubi.frontend.rest.bind.port={{ .Values.server.rest.port }}
      kyuubi.frontend.mysql.bind.port={{ .Values.server.mysql.port }}
      kyuubi.frontend.protocols={{ include "kyuubi.frontend.protocols" . }}
      # Metrics
      kyuubi.metrics.enabled={{ .Values.monitoring.prometheus.enabled }}
      kyuubi.metrics.reporters={{ .Values.metricsReporters }}

  # Configuration files from the list of existing ConfigMaps and Secrets
  filesFrom: []
  #filesFrom:
  #- configMap:
  #    name: kyuubi-configs
  #- secret:
  #    name: kyuubi-secrets
  #- secret:
  #    name: ssl-secrets
  #    items:
  #      - key: key-store
  #        path: certs/keystore.jks
  #      - key: trust-store
  #        path: certs/truststore.jks

# Spark configuration, see https://github.com/apache/spark/tree/master/conf and Spark documentation for more details
sparkConf:
  # $SPARK_CONF_DIR directory
  dir: /opt/spark/conf
  # Configuration files from the specified keys (file name) and values (file content)
  files: ~
  #files:
  #  'spark-defaults.conf': |
  #    spark.submit.deployMode=cluster
  #    spark.kubernetes.container.image=apache/spark:3.5.0
  #    spark.kubernetes.authenticate.driver.serviceAccountName=spark
  #    spark.kubernetes.file.upload.path=s3a://kyuubi/spark
  #    # S3 dependencies
  #    spark.jars.packages=org.apache.hadoop:hadoop-aws:3.3.4,com.amazonaws:aws-java-sdk-bundle:1.12.262
  #    spark.driver.extraJavaOptions=-Divy.cache.dir=/tmp -Divy.home=/tmp
  #    # S3A configuration
  #    spark.hadoop.fs.s3a.impl=org.apache.hadoop.fs.s3a.S3AFileSystem
  #    spark.hadoop.fs.s3a.endpoint=http://object-storage:80
  #    spark.hadoop.fs.s3a.access.key=******
  #    spark.hadoop.fs.s3a.secret.key=********
  #    spark.hadoop.fs.s3a.path.style.access=true
  #    spark.hadoop.fs.s3a.fast.upload=true

  # Configuration files from the list of existing ConfigMaps and Secrets
  filesFrom: []
  #filesFrom:
  #- configMap:
  #    name: spark-configs
  #- secret:
  #    name: spark-secrets
  #- secret:
  #    name: ssl-secrets
  #    items:
  #      - key: key-store
  #        path: certs/keystore.jks
  #      - key: trust-store
  #        path: certs/truststore.jks

# Command to launch Kyuubi server (templated)
command: ~
# Arguments to launch Kyuubi server (templated)
args: ~

# Environment variables (templated)
env: []
# Environment variables from ConfigMaps and Secrets (templated)
envFrom: []

# Additional volumes for Kyuubi pod (templated)
volumes: []
# Additional volumeMounts for Kyuubi container (templated)
volumeMounts: []

# Additional init containers for Kyuubi pod (templated)
initContainers: []
# Additional containers for Kyuubi pod (templated)
containers: []

# Resource requests and limits for Kyuubi pods
resources: {}
#  resources:
#    requests:
#      cpu: 2
#      memory: 4Gi
#    limits:
#      cpu: 4
#      memory: 10Gi

# Liveness probe
livenessProbe:
  enabled: true
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 2
  failureThreshold: 10
  successThreshold: 1

# Readiness probe
readinessProbe:
  enabled: true
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 2
  failureThreshold: 10
  successThreshold: 1

# Constrain Kyuubi pods to nodes with specific node labels
nodeSelector: {}
# Allow to schedule Kyuubi pods on nodes with matching taints
tolerations: []
# Constrain Kyuubi pods to nodes by complex affinity/anti-affinity rules
affinity: {}

# Kyuubi pods security context
securityContext: {}

# Monitoring Kyuubi - Server Metrics
# PROMETHEUS - PrometheusReporter which exposes metrics in Prometheus format
metricsReporters: ~

# Prometheus pod monitor
podMonitor:
  # If enabled, podMonitor for operator's pod will be created
  enabled: false
  # The podMetricsEndpoint contains metrics information such as port, interval, scheme, and possibly other relevant details.
  # This information is used to configure the endpoint from which Prometheus can scrape and collect metrics for a specific Pod in Kubernetes.
  podMetricsEndpoint: []

# Prometheus service monitor
serviceMonitor:
  # If enabled, ServiceMonitor resources for Prometheus Operator are created
  enabled: false
  # The endpoints section in a ServiceMonitor specifies the metrics information for each target endpoint.
  # This allows you to collect metrics from multiple Services across your Kubernetes cluster in a standardized and automated way.
  endpoints: []
  # Additional labels that can be used so ServiceMonitor will be discovered by Prometheus
  labels: {}

# Rules for the Prometheus Operator
prometheusRule:
  # If enabled, a PrometheusRule resource for Prometheus Operator is created
  enabled: false
  # Contents of Prometheus rules file
  groups: []
